"use client";

import type { ImageLoaderProps } from "next/image";

export default function sanityImageLoader({ src, width, quality }: ImageLoaderProps): string {
  const url = new URL(src);

  if (url.protocol !== "https:" || url.hostname !== "cdn.sanity.io" || !url.pathname.startsWith("/images/")) {
    throw new Error("The image loader requires a Sanity CDN image URL.");
  }

  // Preserve the existing crop's aspect ratio at every responsive width.
  // Keep rect/crop parameters generated by Sanity's image URL builder intact.
  const originalWidth = Number(url.searchParams.get("w"));
  const originalHeight = Number(url.searchParams.get("h"));
  if (originalWidth > 0 && originalHeight > 0) {
    url.searchParams.set("h", String(Math.max(1, Math.round(width * originalHeight / originalWidth))));
  }

  url.searchParams.set("w", String(width));
  url.searchParams.set("q", String(quality ?? 75));
  url.searchParams.set("auto", "format");
  if (!url.searchParams.has("fit")) url.searchParams.set("fit", "max");

  return url.toString();
}
